let bundeslaender = [
    {
        "id": 1,
        "name": "Baden-Württemberg",
        "capitalCity": "Stuttgart",
        "imgCountryFlag": `img/Flag_of_Baden-Württemberg.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Baden-Württemberg.svg.png`,
        "Industries": ["Fahrzeugbau", "Maschinenbau", "Informations- und Kommunikationstechnologie", "Gesundheitswesen", "Elektrotechnische", "Industrie", "Metallindustrie", "Chemische und Pharmazeutische Industrie"],
        "population": "11.124.642",
        "particularities": "Baden-Württemberg ist Geburtsort des ersten Automobils: Noch heute sitzt Mercedes-Benz in Stuttgart. Unteranderem gibt es 74 Sternerestaurants und somit die meisten in einem Bundesland.",
        "url": "https://www.baden-wuerttemberg.de/de/startseite/",
        "comments":["Ursprünglich Baden, Schwaben und Hohenzoller", "Badener und Schwaben sticheln sich gegenseitig."]
    },
    {
        "id": 2,
        "name": "Bayern",
        "capitalCity": "München",
        "imgCountryFlag": `img/Flag_of_Bavaria.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Bavaria.svg.png`,
        "Industries": ["Fahrzeugbau", "Maschinenbau", "Gesundheitswesen", "Metallindustrie", "IT", "Biotechnologie", "Medizin-, Energie- und Umwelttechnik", "Elektroindustrie"],
        "population": "13.176.989",
        "particularities": "Blasmusik, Dirndl & Lederhose: Das Oktoberfest in München verbindet Menschen aus aller Welt",
        "url": "https://www.bayern.de",
        "comments":[]
    },
    {
        "id": 3,
        "name": "Berlin",
        "capitalCity": "Berlin",
        "imgCountryFlag": `img/Flag_of_Berlin.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Berlin.svg.png`,
        "Industries": ["Gesundheitswirtschaft", "Life-Science", "Information", "Kommunikation", "Medien", "Kreativwirtschaft", "Forschung und Entwicklung", "Verarbeitendes Gewerbe"],
        "population": "3.677.472",
        "particularities": "Berlin ist ein Lebensgefühl. Hier kommen Menschen aus über 190 verschiedenen Nationen zusammen.",
        "url": "https://www.berlin.de",
        "comments":[]
    },
    {
         "id": 4,
        "name": "Brandenburg",
        "capitalCity": "Potsdam",
        "imgCountryFlag": `img/Flag_of_Brandenburg.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Brandenburg.svg.png`,
        "Industries": ["Gesundheitswesen", "Handel", "Logistik", "Luftfahrttechnik", "Energietechnik", "Automobilindustrie", "Ernährungswirtschaft", "Handwerk"],
        "population": "2.537.868",
        "particularities": "Mit 3.000 Seen ist Brandenburg das gewässerreichste Land der Bundesrepublik.",
        "url": "https://www.brandenburg.de/de/portal/bb1.c.473964.de",
        "comments":[]
    },
    {
        "id": 5,
        "name": "Bremen",
        "capitalCity": "Bremen",
        "imgCountryFlag": `img/Flag_of_Bremen.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Bremen.svg.png`,
        "Industries": ["Fahrzeugbau", "Gesundheitswesen", "Luft- und Raumfahrt", "Logistik und Häfen", "Schiffbau", "Windenergie", "Nahrungsmittelgewerbe", "Information und Kommunikation"],
        "population": "676.463",
        "particularities": "Hansestadt und High-Tech-Standort zugleich: Über 550 Unternehmen sind im Bremer Technologiepark vertreten.",
        "url": "https://www.bremen.de",
        "comments":[]
    },
    {
        "id": 6,
        "name": "Hamburg",
        "capitalCity": "Hamburg",
        "imgCountryFlag": `img/Flag_of_Hamburg.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Hamburgischen_Bürgerschaft.svg.png`,
        "Industries": ["Logistik", "Europas zweitgrößter Hafen", "Maritime Wirtschaft", "Spezialschiffbau", "Schiffbauzulieferer", "Meeres- und Offshore-Technik", "Zivile Luftfahrtindustrie", "Medien und IT", "Gamesbranche", "Erneuerbare Energien", "Life Sciences", "Forschungs- und Produktionsstandort", "Medizintechnik", "Biotechnologie und Pharmaindustrie"],
        "population": "1.853.935",
        "particularities": "Hamburgs Hafen gilt als Tor zur Welt: Schiffe aus aller Welt finden ihren Weg in die Hansestadt.",
        "url": "https://www.hamburg.de",
        "comments":[]
    },
    {
        "id": 7,
        "name": "Hessen",
        "capitalCity": "Wiesbaden",
        "imgCountryFlag": `img/Flag_of_Hesse.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Hesse.svg.png`,
        "Industries": ["Luft- und Raumfahrt", "Automobil- und Zulieferungsindustrie", "Biotechnologie", "Kultur- und Kreativwirtschaft", "Finanzdienstleistungen", "Maschinen- und Anlagebau", "Medizintechnik", "Tourismus"],
        "population": "6.295.017",
        "particularities": "In Hessen steht „Ebbelwoi“ für Apfelwein. Das Getränk ist seit Jahrhunderten ein Teil der hessischen Kultur.",
        "url": "https://hessen.de",
        "comments":[]
    },
    {
        "id": 8,
        "name": "Mecklenburg-Vorpommern",
        "capitalCity": "Schwerin",
        "imgCountryFlag": `img/Flag_of_Mecklenburg-Western_Pomerania.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Mecklenburg-Western_Pomerania_(great).svg.png`,
        "Industries": ["Tourismus", "Gesundheitswirtschaft", "Handel", "Baugewerbe", "Land- und Ernährungswirtschaft"],
        "population": "1.611.160",
        "particularities": "Mit über 2.000 Schlössern hat Mecklenburg-Vorpommern die höchste Dichte an Schlössern weltweit.",
        "url": "https://www.mecklenburg-vorpommern.de/startseite/",
        "comments":[]
    },
    {
        "id": 9,
        "name": "Niedersachsen",
        "capitalCity": "Hannover",
        "imgCountryFlag": `img/Flag_of_Lower_Saxony.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Niedersachsen.svg.png`,
        "Industries": ["Automobilindustrie", "Luft- und Raumfahrt", "Land- und Ernährungswirtschaft", "Energiewirtschaft", "Gesundheitswirtschaft", "Life Sciences und Medizin", "Maritime Wirtschaft", "Elektromobilität", "Informationstechnik"],
        "population": "8.027.031",
        "particularities": "Der Messeplatz Hannover ist weltweit einer der führenden Veranstaltungsorte.",
        "url": "https://www.niedersachsen.de/startseite/",
        "comments":[]
    },
    {
        "id": 10,
        "name": "Nordrhein-Westfalen",
        "capitalCity": "Düsseldorf",
        "imgCountryFlag": `img/Flag_of_North_Rhine-Westphalia.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_North_Rhine-Westfalia.svg.png`,
        "Industries": ["Maschinenbau", "Metallerzeugung und -bearbeitung", "Chemische Industrie", "Gesundheitswesen", "Logistik", "Kredit- und Versicherungsgewerbe", "Information und Kommunikation"],
        "population": "17.924.591",
        "particularities": "NRW ist die Karnevalshochburg. Der Kölner Karneval zählt zu den größten und bekanntesten Karnevalsfesten der Welt.",
        "url": "https://www.land.nrw",
        "comments":[]
    },
    {
        "id": 11,
        "name": "Rheinland-Pfalz",
        "capitalCity": "Mainz",
        "imgCountryFlag": `img/Flag_of_Rhineland-Palatinate.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Rhineland-Palatinate.svg.png`,
        "Industries": ["Chemische und Pharmazeutische Industrie", "Fahrzeugbau", "Metallerzeugung und -bearbeitung", "Maschinenbau", "Umwelttechnologie", "Künstliche Intelligenz", "Gesundheitswirtschaft"],
        "population": "4.106.485",
        "particularities": "Johannes Gutenberg erfand den modernen Buchdruck in Mainz – der rheinland-pfälzischen Landeshauptstadt.",
        "url": "https://www.rlp.de/de/startseite/",
        "comments":[]
    },
    {
        "id": 12,
        "name": "Saarland",
        "capitalCity": "Saarbrücken",
        "imgCountryFlag": `img/Flag_of_Saarland.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Saarlands.svg.png`,
        "Industries": ["Maschinenbau", "Gesundheitswesen", "Automobil-/ Automobilzulieferindustrie", "Stahlindustrie", "Softwareentwicklung / IT"],
        "population": "982.348",
        "particularities": "Ein Drittel des Saarlandes ist mit Waldfläche bedeckt. Das macht es zu einem der waldreichsten Bundesländer.",
        "url": "https://www.saarland.de/DE/home/home_node.html",
        "comments":[]
    },
    {
        "id": 13,
        "name": "Sachsen-Anhalt",
        "capitalCity": "Magdeburg",
        "imgCountryFlag": `img/Flag_of_Saxony-Anhalt_(state).svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Sachsen-Anhalt.svg.png`,
        "Industries": ["Maschinenbau", "Gesundheitswesen", "Metallindustrie", "Logistik", "Ernährungswirtschaft", "Tourismus", "Chemie- und Kunststoffindustrie", "Erneuerbare", "Energien/Wasserstoff", "IT-Wirtschaft mit Schwerpunkt Softwareentwicklung", "Automobilzulieferindustrie"],
        "population": "2.169.253",
        "particularities": "Sachsen-Anhalt besitzt die höchste Dichte an UNESCO-Welterbe-Stätten in Deutschland.",
        "url": "https://www.sachsen-anhalt.de/startseite/",
        "comments":[]
    },
    {
        "id": 14,
        "name": "Sachsen",
        "capitalCity": "Dresden",
        "imgCountryFlag": `img/Flag_of_Saxony.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Saxony.svg.png`,
        "Industries": ["Automobilindustrie", "Maschinen- und Anlagebau", "IKT", "Mikroelektronik", "Umwelt- und Energietechnik"],
        "population": "4.043.002",
        "particularities": "Südlich von Dresden liegt die „Sächsische Schweiz“ – ein beliebtes Reiseziel für Wander- und Kletterfreunde.",
        "url": "https://www.sachsen.de",
        "comments":[]
    },
    {
        "id": 15,
        "name": "Schleswig-Holstein",
        "capitalCity": "Kiel",
        "imgCountryFlag": `img/Flag_of_Schleswig-Holstein.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Schleswig-Holstein.svg.png`,
        "Industries": ["Logistik", "Handwerk", "Tourismus", "Pflege"],
        "population": "2.922.005",
        "particularities": "Seit 2015 deckt Schleswig-Holstein seinen Energiebedarf mit erneuerbaren Energien – vor allem durch Windkraft.",
        "url": "https://www.schleswig-holstein.de/DE/landesportal/landesportal_node.html",
        "comments":[]
    },
    {
        "id": 16,
        "name": "Thüringen",
        "capitalCity": "Erfurt",
        "imgCountryFlag": `img/Flag_of_Thuringia.svg.jpg`,
        "imgStateCoatOfArms": `img/Coat_of_arms_of_Thuringia.svg.png`,
        "Industries": ["Maschinenbau", "Biotechnologie", "Medizintechnik", "Metallverarbeitende Industrie", "Herstellung von elektronischen und optischen Instrumenten und Geräten", "Herstellung von Kraftwagen und Fahrzeugteilen", "Gesundheits- und Sozialwirtschaft", "Kreativwirtschaft Mikro- und Nanotechnologie", "Herstellung und Installation von Geräten zur Nutzung erneuerbarer Energien (GreenTech)"],
        "population": "2.108.863",
        "particularities": "Mitten in Europa suchen innovative Unternehmen Fachkräfte. Ein schöner Platz zum Leben und Arbeiten mit der Familie.",
        "url": "https://thueringen.de",
        "comments":[]
    },
]